import {createTypes} from 'reduxsauce';

export default createTypes(`
  INITIALIZE
  INITIALIZE_SUCCESS

  APP_STATE

  REGISTER
  REGISTER_SUCCESS
  REGISTER_FAILURE
  CLEAR_REGISTRATION_SUCCESS_MESSAGE

  REGISTER_PUSH
  REGISTER_PUSH_SUCCESS
  REGISTER_PUSH_FAILURE

  LOGIN
  LOGIN_SUCCESS
  LOGIN_FAILURE

  FB_LOGIN
  FB_LOGIN_SUCCESS
  FB_LOGIN_FAILURE

  GOOGLE_LOGIN
  GOOGLE_LOGIN_SUCCESS
  GOOGLE_LOGIN_FAILURE
  GOOGLE_LOGIN_CANCEL

  GOOGLE_LOGIN_SETUP
  GOOGLE_LOGIN_SETUP_SUCCESS
  GOOGLE_LOGIN_SETUP_FAILURE

  GET_TOKEN
  GET_TOKEN_SUCCESS
  GET_TOKEN_FAILURE

  LOGOUT

  GET_ME
  GET_ME_SUCCESS
  GET_ME_FAILURE

  GET_PROFILE
  GET_PROFILE_SUCCESS
  GET_PROFILE_FAILURE

  RESET_PASSWORD
  RESET_PASSWORD_SUCCESS
  RESET_PASSWORD_FAILURE

  ONE_SIGNAL_IDS_AVAILABLE

  UPDATE_PROFILE
  UPDATE_PROFILE_SUCCESS
  UPDATE_PROFILE_FAILURE

  SELECT_SAFETYCONTACT
  SELECT_ASSIGNEE
  SELECT_BEHAVIOUR

  ADD_FEEDBACK
  ADD_FEEDBACK_SUCCESS
  ADD_FEEDBACK_FAILURE

  ADD_ARTICLE
  ADD_ARTICLE_SUCCESS
  ADD_ARTICLE_FAILURE

  ADD_CONTACT
  ADD_CONTACT_SUCCESS
  ADD_CONTACT_FAILURE
  
  GET_SUBMITTERS
  GET_SUBMITTERS_SUCCESS
  GET_SUBMITTERS_FAILURE
  GET_SUBMITTER
  GET_SUBMITTER_SUCCESS
  GET_SUBMITTER_FAILURE
  GET_REFNUMBER
  GET_REFNUMBER_SUCCESS
  GET_REFNUMBER_FAILURE
  GET_LOCATIONS
  GET_LOCATIONS_SUCCESS
  GET_LOCATIONS_FAILURE
  GET_LOCATION
  GET_LOCATION_SUCCESS
  GET_LOCATION_FAILURE
  GET_CATEGORIES
  GET_CATEGORIES_SUCCESS
  GET_CATEGORIES_FAILURE
  GET_CATEGORY
  GET_CONTACTPERSONS
  GET_CONTACTPERSONS_SUCCESS
  GET_CONTACTPERSONS_FAILURE
  GET_CONTACTPERSON
  GET_CONTACTPERSON_SUCCESS
  GET_CONTACTPERSON_FAILURE
  GET_ASSIGNEES
  GET_ASSIGNEES_SUCCESS
  GET_ASSIGNEES_FAILURE
  GET_ASSIGNEE
  GET_ASSIGNEE_SUCCESS
  GET_ASSIGNEE_FAILURE
  ADD_ASSIGNEE
  UPDATE_ASSIGNEE
  GET_BEHAVIOURS
  GET_BEHAVIOURS_SUCCESS
  GET_BEHAVIOURS_FAILURE
  ADD_BEHAVIOUR
  GET_BEHAVIOURS
  GET_BEHAVIOURS_SUCCESS
  GET_BEHAVIOURS_FAILURE
  GET_BEHAVIOUR
  RESET_SUBMITTER
  RESET_LOCATION
  RESET_CONTACTPERSON
  RESET_CATEGORY
`);
